### ISSUE TITLE
您好，请问GPT4的API似乎不能兼容图片，请问您是如何解决这个问题的呢？

### ISSUE THREAD

**Issue by Drchip61** [HaonanGuo/Remote-Sensing-ChatGPT-Human-Interactive-Remote-Sensing-Task-Solving-with-ChatGPT#5]

**Comment by ChrisGray0626** [comment]
根据我对源码的理解，GPT 只是用来理解自然语言的，真正的图像处理工作还是交由工具实现的。

**Comment by HaonanGuo** [comment]
> _No description provided._

Thanks for your attention on RS ChatGPT. I did not use the gpt4-visual model, since the uploading process is too complex(upload it to a website somewhere before sending it to gpt4). It is not easy to find a website that is fast and supports large files. I think RSChatGPT will support image input within several months. We are working on developing  our own LLM.
